### ISSUE TITLE
arm64?

### ISSUE THREAD

**Issue by gaboentropy** [torognes/swipe#35]
Hi,

Any change you'll produce a version that can be compiled in M1/arm64 macs?

I saw that you did that in other programs, but wasn't able to figure it out for this one.

Best and thanks for writing such useful software.
-Gabo

**Comment by torognes** [comment]
Thanks for the suggestion. It's a lot of work to port it to the arm64 architecture. I don't have any plans to do it soon, but I will consider it in the future. Sorry that I cannot promise anything.

**Comment by gaboentropy** [comment]
Thanks.
